#!/bin/sh
#!/bin/sh
#################################################################
##### File changed for RT-AX... router                      #####
##### Checked RT-AX58U > telfort IPTV + internet : OK       #####
##### Checked RT-AX11000 > KPN IPTV + internet : OK         #####
#################################################################

#################################################################
##### Add VLAN4 as a physical interface (@ WAN PORT)

/sbin/vconfig add eth0 4

#################################################################
##### Request an IP-address and setup static routes

sleep 1
udhcpc -i vlan4 --clientid-none -O msstaticroutes -O staticroutes -V IPTV_RG -s /jffs/scripts/vlan4.script -p /var/run/vlan4.pid -b -O33 -O249
